version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: on-failure
        volumes:
            - ~/Documents/dev/jenkins/jenkins_home:/var/jenkins_home
        container_name: jenkins-starter
